# Generated by Django 4.2.1 on 2023-05-08 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_rename_false_answer_truefalsequestion_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multiplechoicequestion",
            old_name="answers",
            new_name="answer",
        ),
    ]
